-- VisionPaint schema draft
-- Core assumption: integer primary keys for the current app, with auth.user linkage stored on person.auth_user_id.

create extension if not exists pgcrypto;

create table if not exists company (
  id integer generated by default as identity primary key,
  name text not null,
  timezone text not null default 'America/Denver',
  language_code text not null default 'en',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists person (
  id integer generated by default as identity primary key,
  auth_user_id uuid unique,
  name text not null,
  email text,
  phone text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists person_auth_user_id_idx on person (auth_user_id);
create index if not exists person_email_idx on person (email);

create table if not exists company_member (
  company_id integer not null references company (id) on delete cascade,
  person_id integer not null references person (id) on delete cascade,
  role text not null default 'crew'
    check (role in ('owner', 'admin', 'manager', 'crew')),
  status text not null default 'active'
    check (status in ('invited', 'active', 'disabled')),
  invited_at timestamptz,
  joined_at timestamptz,
  primary key (company_id, person_id)
);

create index if not exists company_member_person_id_idx on company_member (person_id);

create table if not exists client (
  id integer generated by default as identity primary key,
  company_id integer not null references company (id) on delete cascade,
  name text not null,
  billing_email text,
  phone text,
  address_line1 text,
  address_line2 text,
  city text,
  state_region text,
  postal_code text,
  country_code text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists client_company_id_idx on client (company_id);
create index if not exists client_name_idx on client (name);

create table if not exists client_contact (
  client_id integer not null references client (id) on delete cascade,
  person_id integer not null references person (id) on delete cascade,
  role text not null default 'contact'
    check (role in ('owner', 'contact', 'billing', 'estimator', 'other')),
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (client_id, person_id)
);

create index if not exists client_contact_person_id_idx on client_contact (person_id);

create table if not exists job (
  id integer generated by default as identity primary key,
  company_id integer not null references company (id) on delete cascade,
  client_id integer references client (id) on delete set null,
  created_by_person_id integer references person (id) on delete set null,
  title text not null,
  description text,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'in_progress', 'completed', 'cancelled')),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'urgent')),
  address_line1 text,
  address_line2 text,
  city text,
  state_region text,
  postal_code text,
  country_code text,
  scheduled_start_at timestamptz,
  scheduled_end_at timestamptz,
  due_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists job_company_id_status_idx on job (company_id, status);
create index if not exists job_company_id_due_at_idx on job (company_id, due_at);
create index if not exists job_client_id_idx on job (client_id);
create index if not exists job_created_by_person_id_idx on job (created_by_person_id);

create table if not exists job_assignment (
  job_id integer not null references job (id) on delete cascade,
  person_id integer not null references person (id) on delete cascade,
  assignment_role text not null default 'crew'
    check (assignment_role in ('lead', 'crew', 'prep', 'supervisor')),
  assigned_at timestamptz not null default now(),
  unassigned_at timestamptz,
  primary key (job_id, person_id)
);

create index if not exists job_assignment_person_id_idx on job_assignment (person_id);

create table if not exists time_entry (
  id integer generated by default as identity primary key,
  job_id integer not null references job (id) on delete cascade,
  person_id integer not null references person (id) on delete cascade,
  clock_in_at timestamptz not null,
  clock_out_at timestamptz,
  break_minutes integer not null default 0 check (break_minutes >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists time_entry_job_id_clock_in_at_idx on time_entry (job_id, clock_in_at desc);
create index if not exists time_entry_person_id_clock_in_at_idx on time_entry (person_id, clock_in_at desc);

create table if not exists time_break (
  id integer generated by default as identity primary key,
  time_entry_id integer not null references time_entry (id) on delete cascade,
  break_start_at timestamptz not null,
  break_end_at timestamptz,
  break_type text not null default 'lunch'
    check (break_type in ('lunch', 'rest', 'other')),
  notes text
);

create index if not exists time_break_time_entry_id_idx on time_break (time_entry_id);

create table if not exists job_note (
  id integer generated by default as identity primary key,
  job_id integer not null references job (id) on delete cascade,
  author_person_id integer references person (id) on delete set null,
  note text not null,
  created_at timestamptz not null default now()
);

create index if not exists job_note_job_id_created_at_idx on job_note (job_id, created_at desc);

create table if not exists job_status_history (
  id integer generated by default as identity primary key,
  job_id integer not null references job (id) on delete cascade,
  from_status text
    check (from_status in ('scheduled', 'in_progress', 'completed', 'cancelled')),
  to_status text not null
    check (to_status in ('scheduled', 'in_progress', 'completed', 'cancelled')),
  changed_by_person_id integer references person (id) on delete set null,
  changed_at timestamptz not null default now(),
  reason text,
  notes text
);

create index if not exists job_status_history_job_id_changed_at_idx on job_status_history (job_id, changed_at desc);

create table if not exists job_area (
  id integer generated by default as identity primary key,
  job_id integer not null references job (id) on delete cascade,
  parent_job_area_id integer references job_area (id) on delete cascade,
  name text not null,
  status text not null default 'not_started'
    check (status in ('not_started', 'in_progress', 'completed', 'blocked')),
  sort_order integer not null default 0,
  notes text,
  started_at timestamptz,
  completed_at timestamptz
);

create index if not exists job_area_job_id_sort_order_idx on job_area (job_id, sort_order);

create table if not exists job_photo (
  id integer generated by default as identity primary key,
  job_id integer not null references job (id) on delete cascade,
  job_area_id integer references job_area (id) on delete set null,
  job_status text not null
    check (job_status in ('scheduled', 'in_progress', 'completed', 'cancelled')),
  uploaded_by_person_id integer references person (id) on delete set null,
  photo_kind text not null default 'progress'
    check (photo_kind in ('before', 'after', 'progress', 'reference')),
  storage_path text not null,
  caption text,
  taken_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists job_photo_job_id_created_at_idx on job_photo (job_id, created_at desc);
create index if not exists job_photo_job_area_id_idx on job_photo (job_area_id);

create table if not exists checklist_template (
  id integer generated by default as identity primary key,
  company_id integer not null references company (id) on delete cascade,
  name text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists checklist_template_company_id_is_default_idx on checklist_template (company_id, is_default);

create table if not exists checklist_template_item (
  id integer generated by default as identity primary key,
  checklist_template_id integer not null references checklist_template (id) on delete cascade,
  title text not null,
  sort_order integer not null default 0,
  is_required boolean not null default true
);

create index if not exists checklist_template_item_template_id_sort_order_idx
  on checklist_template_item (checklist_template_id, sort_order);

create table if not exists job_checklist_item (
  job_id integer not null references job (id) on delete cascade,
  template_item_id integer not null references checklist_template_item (id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'done', 'not_applicable')),
  completed_by_person_id integer references person (id) on delete set null,
  completed_at timestamptz,
  notes text,
  primary key (job_id, template_item_id)
);

create index if not exists job_checklist_item_template_item_id_idx on job_checklist_item (template_item_id);
