drop schema if exists private cascade;

drop table if exists public.job_checklist_item cascade;
drop table if exists public.checklist_template_item cascade;
drop table if exists public.checklist_template cascade;
drop table if exists public.job_photo cascade;
drop table if exists public.job_area cascade;
drop table if exists public.job_status_history cascade;
drop table if exists public.job_note cascade;
drop table if exists public.time_break cascade;
drop table if exists public.time_entry cascade;
drop table if exists public.job_assignment cascade;
drop table if exists public.client_contact cascade;
drop table if exists public.client cascade;
drop table if exists public.company_member cascade;
drop table if exists public.job cascade;
drop table if exists public.person cascade;
drop table if exists public.company cascade;

create extension if not exists pgcrypto;

create table public.company (
  id integer generated by default as identity primary key,
  name text not null,
  timezone text not null default 'America/Denver',
  language_code text not null default 'en',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.company (id, name)
values (1, 'VisionPaint')
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.company', 'id'),
  greatest(coalesce((select max(id) from public.company), 1), 1),
  true
);

create table public.person (
  id integer generated by default as identity primary key,
  auth_user_id uuid,
  name text not null,
  email text,
  phone text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index person_auth_user_id_key
  on public.person (auth_user_id)
  where auth_user_id is not null;

create index person_email_idx on public.person (email);

create table public.company_member (
  company_id integer not null references public.company (id) on delete cascade,
  person_id integer not null references public.person (id) on delete cascade,
  role text not null default 'crew'
    check (role in ('owner', 'admin', 'manager', 'crew')),
  status text not null default 'active'
    check (status in ('invited', 'active', 'disabled')),
  invited_at timestamptz,
  joined_at timestamptz,
  primary key (company_id, person_id)
);

create index company_member_person_id_idx on public.company_member (person_id);

create table public.client (
  id integer generated by default as identity primary key,
  company_id integer not null references public.company (id) on delete cascade,
  name text not null,
  billing_email text,
  phone text,
  address_line1 text,
  address_line2 text,
  city text,
  state_region text,
  postal_code text,
  country_code text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index client_company_id_idx on public.client (company_id);
create index client_name_idx on public.client (name);

create table public.client_contact (
  client_id integer not null references public.client (id) on delete cascade,
  person_id integer not null references public.person (id) on delete cascade,
  role text not null default 'contact'
    check (role in ('owner', 'contact', 'billing', 'estimator', 'other')),
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (client_id, person_id)
);

create index client_contact_person_id_idx on public.client_contact (person_id);

create table public.job (
  id integer generated by default as identity primary key,
  company_id integer not null default 1 references public.company (id) on delete cascade,
  client_id integer references public.client (id) on delete set null,
  created_by_person_id integer references public.person (id) on delete set null,
  title text not null,
  description text,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'in_progress', 'completed', 'cancelled')),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'urgent')),
  address_line1 text,
  address_line2 text,
  city text,
  state_region text,
  postal_code text,
  country_code text,
  scheduled_start_at timestamptz,
  scheduled_end_at timestamptz,
  due_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index job_company_id_status_idx on public.job (company_id, status);
create index job_company_id_due_at_idx on public.job (company_id, due_at);
create index job_client_id_idx on public.job (client_id);
create index job_created_by_person_id_idx on public.job (created_by_person_id);

create table public.job_assignment (
  job_id integer not null references public.job (id) on delete cascade,
  person_id integer not null references public.person (id) on delete cascade,
  assignment_role text not null default 'crew'
    check (assignment_role in ('lead', 'crew', 'prep', 'supervisor')),
  assigned_at timestamptz not null default now(),
  unassigned_at timestamptz,
  primary key (job_id, person_id)
);

create index job_assignment_person_id_idx on public.job_assignment (person_id);

create table public.time_entry (
  id integer generated by default as identity primary key,
  job_id integer not null references public.job (id) on delete cascade,
  person_id integer not null references public.person (id) on delete cascade,
  clock_in_at timestamptz not null,
  clock_out_at timestamptz,
  break_minutes integer not null default 0 check (break_minutes >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index time_entry_job_id_clock_in_at_idx on public.time_entry (job_id, clock_in_at desc);
create index time_entry_person_id_clock_in_at_idx on public.time_entry (person_id, clock_in_at desc);

create table public.time_break (
  id integer generated by default as identity primary key,
  time_entry_id integer not null references public.time_entry (id) on delete cascade,
  break_start_at timestamptz not null,
  break_end_at timestamptz,
  break_type text not null default 'lunch'
    check (break_type in ('lunch', 'rest', 'other')),
  notes text
);

create index time_break_time_entry_id_idx on public.time_break (time_entry_id);

create table public.job_note (
  id integer generated by default as identity primary key,
  job_id integer not null references public.job (id) on delete cascade,
  author_person_id integer references public.person (id) on delete set null,
  note text not null,
  created_at timestamptz not null default now()
);

create index job_note_job_id_created_at_idx on public.job_note (job_id, created_at desc);

create table public.job_status_history (
  id integer generated by default as identity primary key,
  job_id integer not null references public.job (id) on delete cascade,
  from_status text
    check (from_status in ('scheduled', 'in_progress', 'completed', 'cancelled')),
  to_status text not null
    check (to_status in ('scheduled', 'in_progress', 'completed', 'cancelled')),
  changed_by_person_id integer references public.person (id) on delete set null,
  changed_at timestamptz not null default now(),
  reason text,
  notes text
);

create index job_status_history_job_id_changed_at_idx on public.job_status_history (job_id, changed_at desc);

create table public.job_area (
  id integer generated by default as identity primary key,
  job_id integer not null references public.job (id) on delete cascade,
  parent_job_area_id integer references public.job_area (id) on delete cascade,
  name text not null,
  status text not null default 'not_started'
    check (status in ('not_started', 'in_progress', 'completed', 'blocked')),
  sort_order integer not null default 0,
  notes text,
  started_at timestamptz,
  completed_at timestamptz
);

create index job_area_job_id_sort_order_idx on public.job_area (job_id, sort_order);

create table public.job_photo (
  id integer generated by default as identity primary key,
  job_id integer not null references public.job (id) on delete cascade,
  job_area_id integer references public.job_area (id) on delete set null,
  job_status text not null
    check (job_status in ('scheduled', 'in_progress', 'completed', 'cancelled')),
  uploaded_by_person_id integer references public.person (id) on delete set null,
  photo_kind text not null default 'progress'
    check (photo_kind in ('before', 'after', 'progress', 'reference')),
  storage_path text not null,
  caption text,
  taken_at timestamptz,
  created_at timestamptz not null default now()
);

create index job_photo_job_id_created_at_idx on public.job_photo (job_id, created_at desc);
create index job_photo_job_area_id_idx on public.job_photo (job_area_id);

create table public.checklist_template (
  id integer generated by default as identity primary key,
  company_id integer not null references public.company (id) on delete cascade,
  name text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index checklist_template_company_id_is_default_idx on public.checklist_template (company_id, is_default);

create table public.checklist_template_item (
  id integer generated by default as identity primary key,
  checklist_template_id integer not null references public.checklist_template (id) on delete cascade,
  title text not null,
  sort_order integer not null default 0,
  is_required boolean not null default true
);

create index checklist_template_item_template_id_sort_order_idx
  on public.checklist_template_item (checklist_template_id, sort_order);

create table public.job_checklist_item (
  job_id integer not null references public.job (id) on delete cascade,
  template_item_id integer not null references public.checklist_template_item (id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'done', 'not_applicable')),
  completed_by_person_id integer references public.person (id) on delete set null,
  completed_at timestamptz,
  notes text,
  primary key (job_id, template_item_id)
);

create index job_checklist_item_template_item_id_idx on public.job_checklist_item (template_item_id);
